name: app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  concentric_transition: ^1.0.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  flutter_html: ^2.1.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.1.0
  http: ^0.13.1
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2
  flutter_riverpod: ^0.14.0+3
  image_picker: ^0.8.3+2
  permission_handler: ^8.1.4+2
  device_preview: ^0.7.4
  flutter_local_notifications: ^9.0.0
  flutter_native_timezone: ^2.0.0
  flutter_email_sender: ^5.0.2
  connectivity: ^3.0.6
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.4
  cached_network_image: ^3.1.0

  # firebase_messaging: ^10.0.7
  # firebase_core: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/onboarding/
    - images/recipes/
    - images/icon/
    - images/calories/
    - images/calories/breakfast/
    - images/calories/dinner/
    - images/calories/snacks/
    - images/calories/lunch/
    - images/Settings/
    - images/login/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalooBhaina
      fonts:
        - asset: fonts/BalooBhaina2-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
